### ISSUE TITLE
Cannot install this module on python 3.12.0a2

### ISSUE THREAD

**Issue by Steven7559** [jithurjacob/Windows-10-Toast-Notifications#114]
l can't install this module on python 3.12.0a2,pip says that "SyntaxError" appears in a certain line of code — a set of parentheses is missing after the “print” .I want to find the program that is faulty, but my operating system tells me that the directory does not exist. I put the error code into a text document, please take a look.
Link:
[1.txt](https://github.com/jithurjacob/Windows-10-Toast-Notifications/files/10471199/1.txt)

**Comment by mbit-gh** [comment]
Hi, I'm trying to workout a solution for this issue.

First of all, I couldn't properly re-build the module into its .whl file without having to fix 2 things beforehand:

1 - **parse_requirements import module was outdated**, the current pip version (23.0.1) is structured differently and the code needed to grab parse_requirements from another directory.

2 - **ParsedRequirement class doesn't have an attribute 'req'**, it might have had it in the past, but now seems to be updated to 'requirement', so attrgetter input had to be fixed.

will do a pull request for this two problems, but still, _**the issue you are facing seems to reside somewhere in the building scripts of Python 3.12**_, as the _temporal setup.py_ made when building the project is full of SyntaxError's, but the same "_fixed_" .whl version I made builds without problems on Python 3.11

**Comment by mbit-gh** [comment]
Hi, the problem is that pip can't retrieve the correspondent version of the required module '**Pywin32**'.
This is due it's package administrators need to upload their package (wich has already been updated with Python 3.12 support) to have the correspondent wheel tags for pip to match the compatibility with Python 3.12.

The good thing is that you can manually fix the tags and pip will be able to install Pywin32, which will then let you install **win10toast** without problems. To do so you only need to change the **Pywin32 .whl file name** as follows in this example:

**Python 3.10 Pywin32 wheel tag**: pywin32-305-cp310-cp310-win_arm64.whl
**Python 3.12 Pywin32 wheel tag**: pywin32-305-cp312-cp312-win_arm64.whl

It will work for any platform you are using, just change the tag _cp_ and pip will be able to match the environment compatibility.

after that just run `pip install win10toast`

Hope this helps!

**Comment by Steven7559** [comment]
thanks
