### ISSUE TITLE
Duration not working

### ISSUE THREAD

**Issue by ahmedsadman** [jithurjacob/Windows-10-Toast-Notifications#20]
No matter how much duration value set, the toast always destructs after some specified time (around 3 seconds). Please take a look into this.

**Comment by vascocosta** [comment]
I confirm this issue.

**Comment by jithurjacob** [comment]
As per my research this has been deprecated after Vista [source](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773352(v=vs.85).aspx)

I was hoping that I could have the notification displayed using sleep but as it turns out I was wrong. The duration parameter would be removed in the next release.

**Comment by MagTun** [comment]
It also had this bug but since I updated to Windows 10  version 1809, the duration parameter is working.
