### ISSUE TITLE
Icon appears small

### ISSUE THREAD

**Issue by rogershijin** [jithurjacob/Windows-10-Toast-Notifications#24]
I used a 256x256 pixel .ico file for the icon but the icon is rather small.  I think it might be an issue with my high dpi screen.  

![image](https://user-images.githubusercontent.com/27650355/33586913-bf879fcc-d939-11e7-9c1a-ef6c644b9d5f.png)

Is there any way to make the icon appear larger? Thank you very much.

**Comment by jithurjacob** [comment]
Hi, as per my understanding the icons shown in the tiles are having a fixed size. It is possible that icons are appearing to be small due to high dpi. 

Advanced toast types are currently not targeted for this package
https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/toast-notification-and-action-center-overview-for-windows-10/
